FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

# Ensure we have the tools we need
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 5000

# We don't restore or build here because we mount the source code directly
# and rely on `dotnet watch` to do that automatically when it starts.

CMD ["dotnet", "watch", "run", "--project", "EnglishApp.Api/EnglishApp.Api.csproj", "--urls", "http://0.0.0.0:5000"]
